version: '3'
services:
    web:
        build:
            context: ./web
        ports:
            - '3001:3000'
        depends_on:
            - gateway
        volumes:            
            - ./web:/app/             
            - /app/node_modules
    gateway:
        build:            
            context: ./gateway            
        ports:
            - '8081:8080'                   
        depends_on:             
            - server
        volumes:            
            - ./gateway:/app            
            - /app/node_modules
    server:
        build:            
            context: ./server            
        ports:
            - '5001:5000'                   
        depends_on:             
            - db
        volumes:            
            - ./server:/app            
            - /app/node_modules        
    db:
        build:            
            context: ./db        
        volumes: 
            - db-volume:/var/lib/postgresql/data
        ports:            
            - '5433:5432'       
volumes:
    db-volume: